// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(EmployyContext))]
    [Migration("20241017051018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Models.Employy", b =>
                {
                    b.Property<int>("EmployyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployyId");

                    b.ToTable("Employy");
                });

            modelBuilder.Entity("Models.EmployyLeave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumOfDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaveId");

                    b.ToTable("EmployyLeave");
                });
#pragma warning restore 612, 618
        }
    }
}
